/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsPutOptions {
  title?: string
  uri?: string
  tags?: Array<string>
  timestamp?: number
}
export interface SearchHit {
  frameId: number
  score: number
  snippet: string
}
export interface JsTimelineEntry {
  frameId: number
  /** Unix epoch seconds (i64 cast to f64; lossless for positive timestamps). */
  timestamp: number
  preview: string
  uri?: string
}
export interface BrainStats {
  frameCount: number
  fileSize: number
  segmentSizes: SegmentSizes
}
export interface SegmentSizes {
  data: number
  lex: number
  timeIndex: number
  temporalTrack: number
  sketchTrack: number
}
export declare class PetBrain {
  /**
   * Create a new .mv2 brain file at the given path.
   * Throws if the file already exists.
   *
   * Note: The pre-existence check is not atomic (TOCTOU) but Memvid::create()
   * does not enforce uniqueness itself, so this guard is necessary for AC-2.
   * In practice, pet brain files are created by a single agent process, so
   * the race window is negligible.
   */
  static create(path: string): PetBrain
  /**
   * Open an existing .mv2 brain file. WAL auto-replays on open.
   * Throws if the file does not exist.
   */
  static open(path: string): PetBrain
  /**
   * Ingest a Buffer into the brain as a new frame.
   * Returns the frame sequence number (u64 mapped to f64; safe for pet brain
   * scale -- guarded by MAX_SAFE_INTEGER check).
   */
  putBytes(data: Buffer, options?: JsPutOptions | undefined | null): number
  /** Flush WAL, rebuild indices, write TOC. */
  commit(): void
  /**
   * Returns a 64-character lowercase hex string: the BLAKE3 composite hash
   * of deterministic segments only (frames primary checksum, lex checksum,
   * time index checksum, temporal track checksum, sketch track checksum).
   * Vec index (HNSW) is excluded.
   *
   * **Important:** Call `commit()` before `hash()`. This method reads the TOC
   * from the committed file on disk. Uncommitted WAL data is not reflected
   * in the hash.
   */
  hash(): string
  /**
   * Full-text (Tantivy/lex) search. Returns SearchHit[] with frameId, score, snippet.
   * Vec (HNSW) search is disabled; this is lex-only.
   */
  search(query: string, topK: number): Array<SearchHit>
  /** Returns timeline entries in chronological order. */
  timeline(limit?: number | undefined | null): Array<JsTimelineEntry>
  /** Returns brain stats: frameCount, fileSize, segmentSizes. */
  stats(): BrainStats
  /**
   * Release the file handle and native resources.
   * Subsequent method calls will throw.
   */
  close(): void
}
